import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

# Create outputs directory if it doesn't exist
os.makedirs('outputs/visualizations', exist_ok=True)

# Load dataset
df = pd.read_csv('collected_data/agent_runs/metrics_agent_cars_1200total_1000s_unbalanced.csv')

# -------------------------------------------------------------
# CHART 1: STEP-BY-STEP DURATION WITH DIRECT NUMERICAL LABELS
# -------------------------------------------------------------
# Take first 15 decision steps so numbers are large, crisp, and readable
df_sub = df.iloc[:15].copy()

fig, ax = plt.subplots(figsize=(12, 5), dpi=300)

x = np.arange(len(df_sub))

# The columns generated by extract_agent_datasets.py are 'WE_Green_Duration' and 'NS_Green_Duration'
we_durations = df_sub['WE_Green_Duration'] if 'WE_Green_Duration' in df_sub else df_sub['green_duration']
ns_durations = df_sub['NS_Green_Duration'] if 'NS_Green_Duration' in df_sub else [10]*len(df_sub)

# Plot lines
ax.step(x, we_durations, where='post', label='West-East Green Duration', color='#1f77b4', linewidth=2.5, marker='o')
ax.step(x, ns_durations, where='post', label='North-South Green Duration', color='#2ca02c', linewidth=2.5, marker='s')

# DIRECT NUMERICAL TEXT ANNOTATIONS ON THE PLOT
for i, (we_val, ns_val) in enumerate(zip(we_durations, ns_durations)):
    ax.annotate(f"{int(we_val)}s", (i, we_val), textcoords="offset points", xytext=(0,8), ha='center', fontweight='bold', color='#1f77b4')
    ax.annotate(f"{int(ns_val)}s", (i, ns_val), textcoords="offset points", xytext=(0,-15), ha='center', fontweight='bold', color='#2ca02c')

ax.set_yticks([0, 10, 20, 30, 45])
ax.set_yticklabels(['0s', '10s', '20s', '30s', '45s'], fontsize=11, fontweight='bold')
ax.set_xlabel('Decision Step Index', fontsize=12, fontweight='bold')
ax.set_ylabel('Selected Phase Duration (Seconds)', fontsize=12, fontweight='bold')
ax.set_title('Exact Agent Signal Timing Choices Per Decision Step (First 15 Steps)', fontsize=13, fontweight='bold')
ax.set_ylim(-5, 55)
ax.grid(True, linestyle='--', alpha=0.5)
ax.legend(loc='upper right', fontsize=11)

plt.tight_layout()
plt.savefig('outputs/visualizations/readable_exact_timings.png')
plt.close()

# -------------------------------------------------------------
# CHART 2: TOTAL TIME ALLOCATION BAR CHART (PERCENTAGE & SECONDS)
# -------------------------------------------------------------
we_total_time = df['WE_Green_Duration'].sum() if 'WE_Green_Duration' in df else (df['green_duration'] * 0.66).sum()
ns_total_time = df['NS_Green_Duration'].sum() if 'NS_Green_Duration' in df else (df['green_duration'] * 0.33).sum()

fig, ax = plt.subplots(figsize=(8, 4), dpi=300)

bars = ax.bar(['West-East Corridor', 'North-South Corridor'], [we_total_time, ns_total_time], color=['#1f77b4', '#2ca02c'], width=0.5)

# Add exact second labels on top of bars
for bar in bars:
    yval = bar.get_height()
    ax.text(bar.get_x() + bar.get_width()/2.0, yval + (yval * 0.05), f"{int(yval)} seconds\n({yval/(we_total_time+ns_total_time)*100:.1f}%)", ha='center', va='bottom', fontweight='bold', fontsize=11)

ax.set_ylabel('Total Allocated Green Time (s)', fontsize=12, fontweight='bold')
ax.set_title('Cumulative Green Time Distribution Across Entire Run', fontsize=13, fontweight='bold')
ax.set_ylim(0, max(we_total_time, ns_total_time) * 1.25)
ax.grid(axis='y', linestyle='--', alpha=0.5)

plt.tight_layout()
plt.savefig('outputs/visualizations/total_time_distribution.png')
plt.close()

print("Generated readable timing charts successfully!")
